spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notificationdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:ima123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
  mail:
    host: smtp.example.com    # replace in real deployments
    port: 587
    username: your-smtp-username
    password: your-smtp-password
    properties:
      mail:
        smtp:
          auth: true
          "[starttls.enable]": true

server:
  port: ${SERVER_PORT:1002}

logging:
  level:
    root: INFO
    '[com.example]': DEBUG
